// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"--BASIC Plugins-------","status":false,"description":"--------------------------------------------------------------------","parameters":{}},
{"name":"rpg_basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"Rendering Mode":"Auto","Cache Limit":"10","Screen Width":"960","Screen Height":"720","UI Area Width":"832","UI Area Height":"624","Battle Formation Placement":"Adapt UI","Always Dash":"false","Text Speed":"1","Auto Save File ID":"0","Error Message":"Error occurred. Please ask to the creator of this game.","Show Error Detail":"true","Enable Progress Bar":"true","Max Rendering FPS":"0","---Full Screen & Exit---":"","Default Full Screen":"false","Full Screen Option Name":"Full Screen","Add Shutdown to Title":"true","Shutdown Command Name":"Shutdown","Add Shutdown to Game End":"true"}},
{"name":"SAN_AnalogMove","status":true,"description":"アナログムーブ 3.2.0\nパーティキャラクターの移動をドット移動に変更します。","parameters":{}}
];
